version: '3.7'

services:
  livedl:
    image: jim60105/live-dl
    # build: ./live-dl
    # image: live-dl
    restart: unless-stopped
    volumes:
      - ../YoutubeRecordings:/youtube-dl
      - ./Monitor:/Monitor:ro
      - ./start.sh:/start.sh:ro
      # Cookies binding cannot be achieved with Docker secrets, because the cookies file must be writable.
      - ./cookies.txt:/usr/src/app/cookies.txt
      - ./config_live-dl.yml:/usr/src/app/config.yml:ro
      # If necessary, bind the callback script to /usr/src/app/callback.sh.
      - ./download_again.sh:/usr/src/app/callback.sh:ro
      - ./prune_dir.sh:/usr/src/app/prune_dir.sh:ro
    env_file:
      - .env
    entrypoint: bash /start.sh
    # Logging to LogServer
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:12201"

  youtube-dl-server:
    image: jim60105/youtube-dl-server
    # build: ./youtube-dl-server
    # image: youtube-dl-server
    restart: unless-stopped
    volumes:
      - ../YoutubeRecordings:/youtube-dl
      - ./config_youtube-dl-server.yml:/app_config/config.yml:ro
      - ./cookies.txt:/cookies.txt
    env_file:
      - .env
    environment:
      - LETSENCRYPT_HOST=${HOST}
      - VIRTUAL_HOST=${HOST}
    networks:
      - proxy-tier
    # Logging to LogServer
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:12201"

  jobber:
    image: blacklabelops/jobber:docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../YoutubeRecordings:/youtube-dl
      - ./prune_dir.sh:/prune_dir.sh:ro
    env_file:
      - .env
    environment:
      - JOB_NAME1=PruneOldFiles
      - JOB_COMMAND1=/bin/bash /prune_dir.sh /youtube-dl ${DelPercentage}
      - JOB_TIME1=0 0 1 * * * #Exec per Day at UTC 01:00
      - JOB_NOTIFY_ERR1=true
      - JOB_NOTIFY_FAIL1=true
    # Logging to LogServer
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:12201"

networks:
  proxy-tier:
    external: true
    name: proxy-tier
