# Override logging settings to LogServer
version: '3.7'

services:
  livedl:
    env_file:
      - .env
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${LOGSERVER}"

  youtube-dl-server:
    env_file:
      - .env
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${LOGSERVER}"

  jobber:
    env_file:
      - .env
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${LOGSERVER}"

  # backupdl:
  #   env_file:
  #     - .env
  #   logging:
  #     driver: "gelf"
  #     options:
  #       gelf-address: "udp://${LOGSERVER}"
