# Override logging settings to LogServer
version: '3.7'

services:
  livedl:
    env_file:
      - .env
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${LOGSERVER}"

  youtube-dl-server:
    env_file:
      - .env
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${LOGSERVER}"

  jobber:
    env_file:
      - .env
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${LOGSERVER}"
    environment: 
      - JOB_COMMAND2=docker run --rm --env CHANNELS_IN_ARRAY --env AZURE_STORAGE_CONNECTION_STRING_VTUBER --env Max_Download --log-driver gelf --log-opt gelf-address=udp://${LOGSERVER} jim60105/backup-dl


